language: python
python:
  - '2.7'
install: pip install feedgen
script: bash ./deploy.sh
env:
  global:
    GH_REF: github.com/jbzdarkid/jbzdarkid.github.io.git
    secure: ACd9seqH1SV99dk8b1WeimuaQuS88bHnO9mjYWQQ8N9nsHjvfdkl58VMaGtYKwp8BYUokYcmSARuX9Iu3f5bkckelhmYetVSYO02ukPH+a70sGuCj+qUAaN8Np5tbmVzSQrPlgjCxjAYnhOiwF7lzPa4nmhwvVlS39+ZKTkNT5oCqTp8Z+bZle2M/G8+fhI58mBEchepLYZO6ldAk47h3dEQ1DsTpGQQ4uCNF7Wyk6UatB1XIKCW2zZ0leO2ERPycxixqPsjCSz0YR7+9V88YKspxNlRPTgfjUYjr2fZj7IQ9jtc5zgckFq2Dyg9BTcsznsHvwZTyINHm2vXbj8vgRXH5A3lRnTJcWuEP1LrtZ+v0RUbL1lzaq9aRyC4HcD0845vvLA4KRN2AXjPIamwahdbEUcWM6Aq8gIz0RlYv/Fk1RJ788944szSta7DgAhHjVbOk9/R9q6Z3mljLanQLSt1FKglao5G0RYt0f0fD4psphbgHo6IZZyptn041VbbI+FzVUWGpSrpsjlZRW/XW+6EVdHiMjlf2LReDAXYiAUoRzykluttlpHCDxKeRVgBaKtKPsuKEDEmwkBPx7RDdHmxXvnZbCCQwesbWI+GJGSAUnQHDfgUfoIVDsU6J2NqpvABWYK0oQ9D/95XsPl081nUgy9xR7J9S2gF4/+Cgls=
