name: Replicate puzzles
on:
  schedule:
    - cron: '0 1 * * *' # Run the script daily, the script itself controls which reports are run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repo
      uses: actions/checkout@v4
    - name: Setting up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Installing dependencies
      run: pip install requests
    - name: Converting puzzles
      id: validate
      run: python -u .github/workflows/convert.py 0 100
      env:
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        SECRET: ${{ secrets.GPG_KEY }}
    - name: Publishing changes
      run: |
        git config --global user.email "jbzdarkid@users.noreply.github.com"
        git config --global user.name "Validate and publish workflow"
        git add .

        # https://stackoverflow.com/a/68479810
        if ! git diff-index --quiet HEAD; then
          git commit -m "Replicated latest puzzles"
          git push
        fi

