name: Replicate puzzles
on:
  schedule:
    - cron: '0 1 * * *' # Run the script daily, the script itself controls which reports are run
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Installing dependencies
      run: pip install requests
    - name: Converting puzzles
      id: validate
      run: python -u .github/workflows/convert.py 0 100
      env:
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        SECRET: ${{ secrets.GPG_KEY }}
    - name: Publishing changes
      run: |
        git config http.https://github.com/.extraheader AUTHORIZATION: basic {{ $secrets.GITHUB_TOKEN }}
        git add .
        git commit -m "Replicated latest puzzles"
        git push

