name: Replicate puzzles
on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repo
      run: |
        mkdir -p $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git init
        git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        git fetch origin --depth 1 $GITHUB_REF_NAME
        git checkout $GITHUB_REF_NAME
        git config user.email "jbzdarkid@users.noreply.github.com"
        git config user.name "Validate and publish workflow"
        git config http.https://github.com/.extraheader AUTHORIZATION: basic $GITHUB_TOKEN
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Installing dependencies
      run: pip install Flask-SQLAlchemy Flask mysqlclient
    - name: Converting puzzles
      id: validate
      run: python -u .github/workflows/convert.py 0 100
      env:
        SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
        SECRET: ${{ secrets.GPG_KEY }}
    - name: Publishing changes
      run: |
        git add .
        git commit -m "Replicated 100 puzzles"
        # git push
        git show HEAD

